services:
  dockmanz:
    build: .
    image: localhost:5000/dockmanz:latest
    container_name: Dockmanz
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      - virtual-network
    labels:
      dmz.url: http://dockmanz.docker.local/

networks:
  virtual-network:
    external: true
    name: virtual-network